tests/invalid/MethodCall_Invalid_1.whiley:5: unable to resolve name (no match for f(&int,int))
	found method MethodCall_Invalid_1::f(int)->(int)
    f(_this, 1)
    ^
